### ISSUE TITLE
Firmware 1.0.11.6 works

### ISSUE THREAD

**Issue by ghost** [Freeyourgadget/Gadgetbridge#159]
nr. 16780038. Works well, I think no remarks regarding1.0.10.14. Notification vibration seems not to work with GB 0.6.5.

**Comment by cpfeiffer** [comment]
Hmm, do you mean vibration is broken with 0.6.5 in general, or in combination with the new firmware? Can you check if 0.6.4 supports vibration with that firmware?

No vibration would be pretty much a showtopper for me.

**Comment by xphnx** [comment]
Vibration works in general in GB 0.6.5, except for notifications with the new firmware, with FW1.0.9.3 notification vibrations works fine. Same for GB 0.6.3. with FW 1.0.11.6.

I think it behaves same that FW 1.0.10.14:
- activity recognition: no remarks
- connection: Connecting and synchronizing seems to be slightly faster and more reliable than with previous firmware versions. However, for notifications the vibration feature does not work with Gadgetbridge versions prior to 0.6.2.
- battery life: no remarks

**Comment by danielegobbetti** [comment]
@xphnx I just installed fw 1.0.11.6 and notifications *do* work with GB 0.6.5 for me. Which type of vibration pattern have you set?

**Comment by cpfeiffer** [comment]
AFAIU, with 1.0.11.* firmwares, only the generic notification is used, i.e. without any custom patterns?

**Comment by danielegobbetti** [comment]
The pattern should work, it's the coloring that is fixed (green leds).

**Comment by xphnx** [comment]
Vibration for target steps and Band alarms works
But K9 ( and I think SMS and calls) vibration notifications dont do (nor via debug menu). This is not really a problem for me because this feature is not critical for me.

About the connection: It`s still not perfect but is clearly faster than with the 1.0.9.3. Anyway sometimes I have to disconnect and "discover devices" again.

For my part can be closed.

**Comment by danielegobbetti** [comment]
Hi,

I just found out that with new firmware we get triplets like this:
0xff 0xff 0xff 
when the band wasn't worn. I experienced this at first when the memory on the band was full (I let it run for over 2 months without deleting old data), but the same values are read when I let the band on the table for a couple of hours.

It's either the new firmwares, or my band that is getting toast :/ In any case we should ignore triplets like these.

**Comment by danielegobbetti** [comment]
@xphnx can you please check in settings -> miband settings what vibration type you set for the k9 notification? I would like to find out the root of the issue, as everything works fine for me (vibrations included) with the latest FW.

**Comment by xphnx** [comment]
I have set "Short" x 2 for k9 notifications (default?), but changing to "Alarm clock" do the same.

**Comment by danielegobbetti** [comment]
That's interesting. I tried setting short x 2 and indeed the band vibrates only sometimes. Can you please have a look if the green leds are lit when you push "Send as E-Mail" from the debug activity?

For me they are lit consistently, but the vibration is erratic.

**Comment by xphnx** [comment]
None of the leds are lit when pushing the debug buttons (send mail, send sms, incoming call...).
Reboot button works and lights up leds.

**Comment by IzzySoft** [comment]
Closing this as stale (and OP having removed his/her GH account, so no more feedback is possible anyway).
